import React from "react";
import {Activity,BrainCircuit,ShieldCheck,TrendingUp} from "lucide-react"; import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,Legend} from "recharts"; import {trendData} from "../data/demo"; import StatCard from "../components/StatCard";
export default function Analytics({result}){
 const r=result||{score:62,risk:"Moderate",confidence:87};
 return <><div className="pageIntro"><div><span className="kicker">PATTERN MONITORING</span><h2>AI analytics</h2><p>Prototype signals showing how the prediction can be explained and monitored over time.</p></div><span className="pill pillGreen"><span className="liveDot"/> Model online</span></div>
 <div className="statsGrid"><StatCard label="Risk probability" value={(r.score/100).toFixed(2)} sub={r.risk+" risk"}/><StatCard label="Model confidence" value={r.confidence+"%"} sub="Prototype confidence"/><StatCard label="Change vs baseline" value="+14%" sub="Needs monitoring" variant="yellowStat"/><StatCard label="Last analysis" value="Today" sub="Just now"/></div>
 <div className="twoCol"><div className="panel"><div className="panelHead"><div><h3>Distress & mood pattern</h3><span>Last 7 days</span></div></div><div className="chart"><ResponsiveContainer width="100%" height={260}><LineChart data={trendData}><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis yAxisId="left" domain={[0,100]} axisLine={false} tickLine={false}/><YAxis yAxisId="right" orientation="right" domain={[0,10]} axisLine={false} tickLine={false}/><Tooltip/><Legend/><Line yAxisId="left" type="monotone" dataKey="distress" stroke="#6d5dfc" strokeWidth={3} dot={false} name="Distress %"/><Line yAxisId="right" type="monotone" dataKey="mood" stroke="#27b3a1" strokeWidth={3} dot={false} name="Mood / 10"/></LineChart></ResponsiveContainer></div></div>
 <div className="panel"><div className="panelHead"><div><h3>Explainable factors</h3><span>Contributors to current score</span></div><ShieldCheck size={19} className="iconPurple"/></div>{[["Emotional wellbeing",68],["Sleep pattern",54],["Social connection",61]].map(([x,v])=><div className="factor" key={x}><div><b>{x}</b><span>{v}%</span></div><div className="progress"><i style={{width:v+"%"}}/></div></div>)}<div className="notice"><TrendingUp size={18}/><span>Trend changes are more informative when monitored over multiple check-ins.</span></div></div></div>
 <div className="panel pipeline"><div className="panelHead"><div><h3>Model pipeline</h3><span>Example architecture for the SIH implementation</span></div><BrainCircuit className="iconPurple"/></div><div className="pipelineSteps">{["Consent + check-in","Signal preprocessing","Feature extraction","Temporal model","Risk prediction","Human-review routing"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b>{i<5&&<em>→</em>}</div>)}</div></div>
 <div className="disclaimer">⚠️ <b>Prototype notice:</b> These numbers are simulated for demonstration and are not a clinical diagnosis.</div>
 </> }